package tutorial.mr.task1.modelC;

/**
 * The output generated by mapper not necessarily must be a primitive.
 * Again, you can define your our types.
 *
 */
public class OutDatum<T> {
	private T op1;
	
	public OutDatum(T op1) {
		this.op1 = op1;
	}
	
	public T getValue() {
		return op1;
	}
}
