package tutorial.mr.task1.modelC;

/**
 * The output generated by mapper not necessarily must be a primitive.
 * Again, you can define your our types.
 *
 */
public class OutDatum {
	private int op1;
	
	public OutDatum(int op1) {
		this.op1 = op1;
	}
	
	public int getValue() {
		return op1;
	}
}
